drop TABLE if EXISTS person;

create TABLE person (
  id bigint generated by DEFAULT as IDENTITY,
  first_name VARCHAR(255) not null,
  last_name VARCHAR(255) not null
);

insert into person (first_name, last_name) VALUES ('w', 'ys');